= SOLID

== Project `Pizza`

Создайте *CLI* приложение для эмуляции работа пиццерии.

* Приложение представляет собой терминал, за которым работаю персонал пицеррии.
* Классы приложения должны быть построены с учетом принципов *SOLID*.
* Приложение должно иметь нижеприведенную функциональность.

=== Specification of task 1

Пользователю предлагается выбрать из 5 стандартных рецептов пиццы (каждая пицца может содержать различные ингридиенты и их количество).

=== Specification of task 2

Информацию о заказанной пице (время заказа, название, сумма) нужно отобразить на экран и записать в файл, при этом используются ингридиенты из хранилища.

=== Specification of task 3

Добавить для пользователя выбор, каким способом произвести расчет:

* наличными
* банковской картой
* на сайте

=== Specification of task 4

Необходимо добавить систему скидок. Скидка зависит от:

* количества пицц
* дня недели

=== Specification of task 5

Необходимо иметь возможность просмотреть информацию о наличии ингридиентов для пицц.

=== Specification of task 6

Необходимо иметь возможность просмотреть за некий период:

* количество проданных пицц
* выручку
* прибыль

=== Specification of task 7

Если ингридиенты для пицц заканчиваются, то вывести информационное сообщение о тех ингридиентах, которые необходимо приобрести.

=== Specification of task 8*

Пользователь может создать свой рецепт пиццы, для этого он выбирает:

* мясные ингридиенты
* сыр
* овощи
* соус
* тип теста
* тип борда
